import logo from './logo.png';
import hamburgerIcon from './hamburgerIcon.png';
import expandIcon from './icons/expandIcon.svg';
import BRFlagIcon from './icons/BRFlagIcon.svg';
import USFlagIcon from './icons/USFlagIcon.svg';
import SPFlagIcon from './icons/SPFlagIcon.svg';
import FRFlagIcon from './icons/FRFlagIcon.svg';
import closeSvgIcon from './icons/closeSvgIcon.svg';
import heroBackground2 from './images/hero-background.png';
import heroDashboard from './images/hero_dashboard.png';
import btgPactualLogo from './images/btgLogo.svg';
import aeroportoBahiaLogo from './images/aeroBahia.svg';
import rioGaleaoLogo from './images/galeaoLogo.svg';
import chipDevelopment from './icons/chipDevelopment.svg';
import chipGlobal from './icons/chipGlobal.svg';
import chipStrategy from './icons/chipStrategy.svg';
import chatBot from './images/productChatBot.webp';

export const logoImg = logo;
export const mobileClosedIcon = hamburgerIcon;
export const menuExpandIcon = expandIcon;
export const BRIcon = BRFlagIcon;
export const USIcon = USFlagIcon;
export const SPIcon = SPFlagIcon;
export const FRIcon = FRFlagIcon;
export const closeIcon = closeSvgIcon;
export const heroBG = heroBackground2;
export const heroDashboardImage = heroDashboard;
export const btgLogo = btgPactualLogo;
export const aeroBahiaLogo = aeroportoBahiaLogo;
export const galeaoLogo = rioGaleaoLogo;
export const chipDevelopmentIcon = chipDevelopment;
export const chipGlobalIcon = chipGlobal;
export const chipStrategyIcon = chipStrategy;
export const productChatBot = chatBot;
